# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7dvN1bUN-lgMdF7ogOBcdUyfnTm5yXA
"""

from flask import Flask

app = Flask(__name__)

@app.route('/')
def home():
    return "Welcome to the Sumo Simulation!"

if __name__ == '__main__':
    app.run(debug=True)